### ISSUE TITLE
Minify JSON with method

### ISSUE THREAD

**Issue by 360matt** [Simplix-Softworks/SimplixStorage#33]
**Is your feature request related to a problem? Please describe.**
JSON too large

**Describe the solution you'd like**
I would like there to be an option to modify the file, i.e. there is no more space, no comments, and everything to be on one line

**Describe alternatives you've considered**
Remove all space

**Comment by KotlinFactory** [comment]
Hi,
we currently don't have time to implement this.

Regards,
Leonhard
