### ISSUE TITLE
Memory Leaks + Use EntrySet instead KeySet

### ISSUE THREAD

**Issue by 360matt** [Simplix-Softworks/SimplixStorage#34]
I have found a little bug:

In **de.leonhard.storage.Json** at method **write()** :
The writer was not closed.

And,
In **de.leonhard.storage.util.JsonUtils** at **getJsonFromMap()**  :
Use Map.Entry (one time loop) instead of KeySet (loop + find)

**Comment by KotlinFactory** [comment]
Hey, 
thanks for reporting this,
you are absolutely right about the getJsonFromMap method, I will correct that!
The writer is being closed by the @Cleanup annotation from lombok.

Regards,
Leonhardö

**Comment by KotlinFactory** [comment]
Done, thanks again for the feedback!
