### ISSUE TITLE
Another encoding bug

### ISSUE THREAD

**Issue by 360matt** [Simplix-Softworks/SimplixStorage#35]
When I **reload** my server/plugin, the .yml is **corrupted**

* My Intellij IDE is in UTF-8: 
![image](https://user-images.githubusercontent.com/28982110/102716362-b5c83500-42db-11eb-9192-0c936d39a9ca.png)

* My pom.xml have UTF-8 encodage configuration:
![image](https://user-images.githubusercontent.com/28982110/102716389-e60fd380-42db-11eb-9e54-115f3577c72d.png)

How to reproduce (in my case):
* I add the defaults value from a HashMap:
![image](https://user-images.githubusercontent.com/28982110/102716429-31c27d00-42dc-11eb-9c62-003d550a3129.png)
![image](https://user-images.githubusercontent.com/28982110/102716440-40109900-42dc-11eb-85c4-53337d18cdf4.png)
![image](https://user-images.githubusercontent.com/28982110/102716476-70f0ce00-42dc-11eb-8534-27fa47a44aea.png)

The first load the correct encodage, but nexts (re)load corrupt the file
I can't use special character :/

**Comment by KotlinFactory** [comment]
Hey,
thanks for reporting this, currently we are working this out in our support discord.

Regards,
- Leonhard

**Comment by KotlinFactory** [comment]
Should be resolved, please tell if otherwise.

**Comment by JCAguilera** [comment]
Hi! is this fixed? I can't read special characters with Yaml.get(key, def) method

**Comment by KotlinFactory** [comment]
Yes, it should be fixed. Are you using SimplixStorage on Bukkit?
If so please use: 

 -Dfile.encoding=UTF-8 in your run.bat / run.sh file.

If this does not work we are more than happy to help you.

Regards,
Leonhard
