### ISSUE TITLE
[Feature Request] Reload callback

### ISSUE THREAD

**Issue by Ghost-chu** [Simplix-Softworks/SimplixStorage#36]
**Is your feature request related to a problem? Please describe.**
My plugin needs to do something while reloading.
I like auto-reloads, it's smart, but I didn't found some like callback stuff.

**Describe the solution you'd like**
Some thing like:
```java
Config config = LightningBuilder.fromFile( FILE ).reloadCallback( (config) -> { /* do something */ }  ).createConfig();
```

**Describe alternatives you've considered**
nothing

**Additional context**
nope

**Comment by KotlinFactory** [comment]
Hey Ghost-chu,

thats a great idea! We will implement it for the next release!

Regards,
Leonhard

**Comment by KotlinFactory** [comment]
Added in the latest release.
