### ISSUE TITLE
Incorrect data type in YAML file on plugin reload with getOrSetDefault()

### ISSUE THREAD

**Issue by mindsolve** [Simplix-Softworks/SimplixStorage#40]
**Describe the bug**
- Upon reloading a server with a plugin using the `Yaml` configuration, some integer values are rewritten to be strings in that configuration file.
- Based on my testing, only values retrieved with `Yaml#getOrSetDefault()` are rewritten, though I cannot 100% verify this

**To Reproduce**
1. Open a configuation file with the `Yaml` class
   `Yaml config = new Yaml(new File(getDataFolder(), "config.yml"));`
2. Retrieve any integer value with `getOrSetDefault()`
   `config.getOrSetDefault("test.defaulttest", 1);`
3. If the config option didn't exist before: Observe the correct addition of that value as int:
   ```yaml
   test: 
      defaulttest: 1
   ```
4. Restart server/reload plugin
5. Observe changed value:
   ```yaml
   test: 
      defaulttest: '1'
   ```

**Expected behavior**
The configuration value should be saved as integer in the yaml file, and not changed on reload.

**Example code**
```java
Yaml config = new Yaml(new File(getDataFolder(), "config.yml"));
config.setConfigSettings(ConfigSettings.PRESERVE_COMMENTS);
// unmodified config option
config.set("test.test", 1);
config.setDefault("test.test", 2);
getLogger().info(Integer.toString(config.getInt("test.test")));

// config option that magically transforms
config.getOrSetDefault("test.defaulttest", 1);

```

**Version**
(from maven)
```
com.github.simplix-softworks:SimplixStorage:jar:3.2.2
com.esotericsoftware.yamlbeans:yamlbeans:jar:1.13
org.json:json:jar:20200518
```

**Server**
Minecraft: `Paper 1.16.5 v662, implementing API  1.16.5-R0.1-SNAPSHOT`
Java: `Java 11 (OpenJDK 64-Bit Server VM 11.0.11+9) Host: Linux 5.4.106-1-pve (amd64)`

**Additional context**

(1) YAML file after addition of values with code above:
```yaml
test: 
   test: 1
   defaulttest: 1
```

(2) YAML file after server restart/plugin reload:
```yaml
test: 
   test: 1
   defaulttest: '1'
```

**Comment by KotlinFactory** [comment]
Hey mindsolve,

thank you for reporting this issue here and on our Discord server.
We will have a look at it this weekend to fix this.

Regards,
Leonhard

**Comment by mindsolve** [comment]
Hey Leonhard,

I can confirm that your commit 570cef171e0942e308e47d8e2667b83ba93f136a fixed this issue.

Thank you for your fixing this so fast!

Best regards,
Felix
