### ISSUE TITLE
FlatFile#resetPathPrefix

### ISSUE THREAD

**Issue by Croos3r** [Simplix-Softworks/SimplixStorage#47]
**Is your feature request related to a problem? Please describe.**
It's bit boring to write setPathPrefix(null) everytime I have to go to my root section using the lib. Moreover I think it's a more elegant way to reset it using a function made for it.

**Describe the solution you'd like**
Just mapping a new function resetPathPrefix to setPathPrefix(null)

**Comment by KotlinFactory** [comment]
Hey,
that seems like a cool addition. However I'm not sure how useful it would be.
Are you willing to create a PR for this?

Regards,
Leonhard

**Comment by Croos3r** [comment]
> Hey,
> that seems like a cool addition. However I'm not sure how useful it would be.
> Are you willing to create a PR for this?
> 
> Regards,
> Leonhard

I'll read the code of conduct first and PR later ;)

**Comment by Croos3r** [comment]
#51 
Did it !

**Comment by KotlinFactory** [comment]
Thanks, merged!
