### ISSUE TITLE
Unsupported class file major version 60 when compiling in java 16

### ISSUE THREAD

**Issue by Nuckerr** [Simplix-Softworks/SimplixStorage#53]
**Describe the bug**
Whenever I try to compile my 1.17 Bukkit plugin (using java 16), if SimplixStrage is added and shaded, I get the following error while compiling: `Unsupported class file major version 60`. When I remove it, it compiles fine

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new java 16 project
2. Add simplix storage
3. Add relocation
4. Compile
5. See error

**Expected behavior**
It should just build

**Screenshots**
![image](https://user-images.githubusercontent.com/62883418/135447705-0983771c-0dce-4d19-8f55-31391cac3223.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu] Windows
 - Version [e.g. 18.04] 11 (but it shouldnt make any difference if I was on windows 10)
**Java**
 - Version: [e.g. 1.8.0_291] 16

**Additional context**
This is a paper plugin. And the shade plugin version is `3.2.4`

**Comment by KotlinFactory** [comment]
Hey Nuckerr,

thank you for using SimplixStorage.
I'm actively using it on Java16 plugins & it works fine.
Java is also known to be backward-compatible. 
It really seemed like you have some kind of an invalid pom.xml - Did you set your java-version to 16 for the compile task?

Regards,
Leonhard
