### ISSUE TITLE
Toml comments are not preserved

### ISSUE THREAD

**Issue by Leonardo-DGS** [Simplix-Softworks/SimplixStorage#55]
**Describe the bug**
Toml comments are not preserved when setting a value in an existing commented file.

**To Reproduce**
1. Create a Toml file with comments
2. Use a method that changes a value in that file
3. Lines with comments are replaced with empty lines

**Expected behavior**
Preservation of comments in Toml files

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
**Java**
 - Version: 17

**Comment by KotlinFactory** [comment]
Hey Leonardo,

We currently don't have support for preserving comments.

Regards,
 Leonhard

**Comment by Leonardo-DGS** [comment]
@KotlinFactory they will be implemented in future?
