### ISSUE TITLE
HOCON config support

### ISSUE THREAD

**Issue by Leonardo-DGS** [Simplix-Softworks/SimplixStorage#62]
**Is your feature request related to a problem? Please describe.**
It would be useful to make consistent configs for Sponge plugins.

**Describe the solution you'd like**
Support for HOCON files.

**Comment by KotlinFactory** [comment]
Hey,

thank you for your request.
Please create a PR if you can for this.

Regards,
Leonhard

**Comment by KotlinFactory** [comment]
Can not do currently.
