### ISSUE TITLE
Config(yaml) has broken edit with UTF-8 Characters

### ISSUE THREAD

**Issue by tomekatomek123456789** [Simplix-Softworks/SimplixStorage#67]
**Describe the bug**
UTF-8 characters get broken and duplicated every time when config(yml) is edited.

**To Reproduce**
Steps to reproduce the bug:
1. Add some comments with utf-8 characters 
2. Edit config using set(key, object) method 
3. Open file in Notepad++ or Hex Editor
4. See broken config

**Expected behavior**
It should be no corruption of characters when plugin is editing the config file.

**Screenshots**
![image](https://user-images.githubusercontent.com/29521866/147286047-d72a0f77-79db-4733-a172-2b385b09729c.png)

After edit:
![image](https://user-images.githubusercontent.com/29521866/147286122-813877fb-b677-4b6f-85e6-2a5b9886a7df.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
**Java**
 - Version: [ adoptOpenJDK16]

**Comment by KotlinFactory** [comment]
Hey,

thanks for using SimplixStorage & reporting this issue.
We tried to reproduce issues like this multiple times and they usually were always caused rather by usage than by SimplixStorage itself.
However we will have a look at this again.

Regards,
- Leonhard

**Comment by KotlinFactory** [comment]
Any updates from your side on this?

**Comment by KotlinFactory** [comment]
To get this reopened please respond to the issue.
