### ISSUE TITLE
Comments dissappear when adding defaults.

### ISSUE THREAD

**Issue by Profeer** [Simplix-Softworks/SimplixStorage#70]
**Describe the bug**
When I load/create config, the comments dissappear if I use 
`.addDefaultsFromInputStream()`

Using:
`   LightningBuilder.fromFile(new File(location, fileName))
                        .addInputStreamFromResource(fileName) //Optional
                        .setDataType(DataType.SORTED)
                        .setReloadSettings(ReloadSettings.INTELLIGENT)
                        .setConfigSettings(ConfigSettings.PRESERVE_COMMENTS)
                        .createConfig()`
Works, but that wouldnt add defaults from my resource file.
So Need to use  `.addDefaultsFromInputStream()`, 
But that will remove 90% of the comments. Out of like 100x comments like 4 stay on the file for some reason.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
**Java**
 - Version: 18

**Comment by KotlinFactory** [comment]
Hey,

can you try to use the constructor instead please, maybe there is a bug with the builder. Also, make sure to use the latest version. LightningBuilder was renamed to SimplixBuilder.

Regards,
- Leonhard

**Comment by Profeer** [comment]
Decided to extend YamlConfiguration since it nowadays supports block and inline comments. And added my own few methods there. And I tried the newest build with SimplixBuilder and still had same problem. Thanks for ur time:)
