### ISSUE TITLE
Latest release shows wrong version in maven 

### ISSUE THREAD

**Issue by christmascoding** [Simplix-Softworks/SimplixStorage#76]
**Describe the bug**
In the latest release(3.2.5), it shows version 3.2.4 instead of 3.2.5 

**To Reproduce**
1. Go to releases
2. Paste into pom.xml
3. Error, version 3.2.4 doesn't work anymore, latest is 3.2.5

**Expected behavior**
Library imports succesfully

See:
<dependency>
  <groupId>com.github.simplix-softworks</groupId>
  <artifactId>SimplixStorage</artifactId> 
  <version>3.2.4</version>

</dependency>

Version should be 3.2.5

Thanks for maintaining this library. Your work is appreciated

**Comment by KotlinFactory** [comment]
Should be resolved. Comment if this should be reopened.
