### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by LowScarlet** [Simplix-Softworks/SimplixStorage#78]
Example i have player storage like this
Low_Scarlet.json
```
money: 90
```
Low_Scarlet2.json
```
money: 99999
```
Low_Scarlet3.json
```
money: 0
```

How to get top money here?

**Comment by KotlinFactory** [comment]
Hi you would iterate through all values & look for the highest.

Something like
`
var result = 0

for(var value : values) {
 if(value > result) {
  result = value;
 }
}
`

Or even better: https://stackoverflow.com/questions/8304767/how-to-get-maximum-value-from-the-collection-for-example-arraylist

Also you can get all top-level-values by using the `singleLayerKeySet()` method.
You would then have to map them to integers. Using `stream.map` or just by iterating over them & creating a new list with the values of the original one parsed to an Integer using `Integer.parseInt`

**Comment by KotlinFactory** [comment]
Will close this, if you still need help, please let me know then we will reopen this.
